### ISSUE TITLE
Canning machine recipes create cans

### ISSUE THREAD

**Issue by rapus95** [PTOM76/AdvancedReborn#10]
The canning machine recipes always need a single can, but produce different numbers of food cans. Consuming a food can always leaves an empty food can. Thus, we are creating cans out of thin air. The recipes should always need as many cans as there are food cans produced!

**Comment by rapus95** [comment]
![image](https://user-images.githubusercontent.com/5960902/174447516-eae9a50b-c714-4974-b751-f6e37d0ef24b.png)

**Comment by PTOM76** [comment]
Thank you!
fixed
