### ISSUE TITLE
1.19 Server startup crash (REI)

### ISSUE THREAD

**Issue by Geartwo** [PTOM76/AdvancedReborn#13]
In 1.19 REI uses a new entry point, that you have to use instead of rei (rei_server, rei_client or rei_common)
![image](https://user-images.githubusercontent.com/4224642/175401775-5763383f-3cf1-4eb3-b74e-bf4190de8275.png)

ありがとうございます

**Comment by PTOM76** [comment]
Thank you very much for reporting!
the issue will be fixed in the next release
