### ISSUE TITLE
1.19 Nano Helmet: Night Vision Goggles - Unknow item

### ISSUE THREAD

**Issue by Geartwo** [PTOM76/AdvancedReborn#14]
I think the recipe "advanced_reborn:crafting/nano_helmet_2" have the wrong item name for NV Goggles.

advanced_reborn:crafting/nano_helmet_2:
ag4tr:nv_goggles -> gearreborn:nv_googles
![image](https://user-images.githubusercontent.com/4224642/175965298-8d520d58-5f64-486d-b008-d4879f3e6013.png)

**Comment by PTOM76** [comment]
Fixed
