### ISSUE TITLE
Permanent Light Generator loses capacity after leaving single player world and rejoining

### ISSUE THREAD

**Issue by endavis** [PTOM76/AdvancedReborn#27]
I tested this in creative using the highest tier Permanent Light Generator. When I place it for the first time, it is fine. When I logout of my single player world and then log back in, it has been downgraded. This happens to all tiers of the generator. They all go to 8E capacity after logging out and logging back in.

 Screenshots and log attached.
[advanced-reborn-bug.log](https://github.com/PTOM76/AdvancedReborn/files/9664373/advanced-reborn-bug.log)
![First_placement](https://user-images.githubusercontent.com/6662995/192766018-7c25003b-9a15-4ef7-a39b-7741646f5028.png)
![After_logging_back_in](https://user-images.githubusercontent.com/6662995/192765989-c0149783-1dbb-4ea8-8f2c-19269818ba10.png)

**Comment by PTOM76** [comment]
Fixed in 1.1.0.
