### ISSUE TITLE
mcpitanlibarch isn't marked as a dependency in fabric.mod.json

### ISSUE THREAD

**Issue by Witixin1512** [PTOM76/AdvancedReborn#28]
In case someone forgets to download the required file, the following NoClassDefFoundError appears:
```
java.lang.NoClassDefFoundError: ml/pkom/mcpitanlibarch/api/util/TextUtil
	at ml.pkom.advancedreborn.items.ConfigWrench.method_7851(ConfigWrench.java:89)
	at net.minecraft.class_1799.method_7950(class_1799.java:699)
	at net.minecraft.class_310.method_1591(class_310.java:816)
```

I'd be nice if the fabric.mod.json included mcpitanlibarch as a dependency so that FabricLoader gives a more descriptive issue rather than this crash which is unreadable by some users.

Thanks!

**Comment by PTOM76** [comment]
It's true, I just checked. Thank you for your report.
