### ISSUE TITLE
Request for 1.18.1

### ISSUE THREAD

**Issue by Trogdayton** [PTOM76/AdvancedReborn#3]
If possible, can we get a 1.18.1 version? It would be really useful. If it's too much trouble that's fine, just figured I'd ask. Thanks!

**Comment by PTOM76** [comment]
I'll think about it.
And did this mod not work with 1.18.1?

**Comment by Trogdayton** [comment]
got errors. Want the log? It might not be your mod, it was just what was
identified in the crash log.

**Comment by PTOM76** [comment]
Sure thing. i will check the error.

**Comment by Trogdayton** [comment]
https://paste-bin.xyz/47950

**Comment by PTOM76** [comment]
thank you very much!

**Comment by Trogdayton** [comment]
Just FYI I removed your mod and it at least loaded up, though I'm getting datapack errors I'll have to look at now. *sigh*

**Comment by PTOM76** [comment]
Backported to 1.18.1.
https://www.curseforge.com/minecraft/mc-mods/advancedreborn/files/3734832
