### ISSUE TITLE
Can't use Enchanted Books from Enchantment Extractor

### ISSUE THREAD

**Issue by TheGamerX20** [PTOM76/AdvancedReborn#31]
Hello, It seems that you can't use the Enchanted Books that are made in the "Enchantment Extractor" in an Anvil.
the Books also have a different Item Rarity Color, Vanilla's is Yellow while the Enchantment Extractor's Book is Blue.

I am using AdvancedReborn-1.19-1.1.1.jar from CurseForge on MC1.19.2

![image](https://user-images.githubusercontent.com/59514885/201195898-5d2acb7a-95d7-4679-a7f5-631ab88afc05.png)

**Comment by PTOM76** [comment]
Thank you for your reporting.
Fixed in 1.1.2
