### ISSUE TITLE
[Major Fix] Startup Crash with newest version of Tech Reborn & Reborn Core

### ISSUE THREAD

**Issue by HacoKavanah** [PTOM76/AdvancedReborn#7]
Literally nothing else to say.

**Comment by HacoKavanah** [comment]
Any news on this? Gear Reborn got their update out already and there are few essential fixes in the newest version of Tech Reborn that me and my friends can't get to before this is fixed. We love your mod!

**Comment by PTOM76** [comment]
Thank you for your report.
Fixed.
It will be applied in the next release.
